import type { RuleDataFile } from "@gujian/domain";

// 规则数据文件：单一对象字面量，专业人员逐条审阅，不含任何逻辑。
// 加载入口 rule-engine.ts 的 loadRuleData 在运行时做 Zod 校验并计算内容哈希。
// 公式中的标识符先取基准参数，再取同规则集内其他规则的 ruleId 结果。
// 举架系数出处：两套并存规则集转引自 ACA-Builder const.py 对文献的整理
// （见 笔记/代码技术借鉴整合_给执行会话_20260815.md 第 3.1 节），
// 仅作规范选择停靠的方案生成演示，未验证对本项目样本的适用性。

export const HERITAGE_BASELINE_RULE_DATA = {
  schemaVersion: "rule-data-1",
  dataSetId: "heritage-baseline",
  version: "1.0.0",
  programParams: {
    // 尺寸链核对容差：总尺寸与分段之和的允许偏差（workflow 尺寸链规则消费）
    dimensionChainToleranceMm: "1",
  },
  modificationCheck: {
    magnitudeBand: { minRatio: 0.5, maxRatio: 2 },
    anchorPart: "檐柱高",
    mustExceedAnchor: ["檐口高"],
    mustStayBelowAnchor: ["台基"],
    estimateMarkPattern: "（估）|\\(估\\)",
    measurementMatchToleranceMm: 1,
  },
  ruleSets: [
    {
      schemaVersion: "rule-spec-1",
      ruleSetId: "liang-drawings",
      sourceText: "梁思成图纸中采用的举架系数（转引自 ACA-Builder const.py LIFT_RATIO_DEFAULT 注释）",
      version: "1.0.0",
      rules: [
        {
          ruleId: "stepSpan",
          subjectConceptRef: "roof-frame",
          dimension: "均分步架",
          formula: "totalDepthMm / 2 / stepCount",
          baseParams: ["totalDepthMm", "stepCount"],
          tolerance: null,
          sourceText: "步架 =（通进深 / 2）/ 步架数（jiangshu JiangSuan v1.0 举架算法）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftFirst",
          subjectConceptRef: "roof-frame",
          dimension: "檐步举高",
          formula: "stepSpan * 0.5",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "五举 0.5（梁思成图纸系数组第 1 架）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftSecond",
          subjectConceptRef: "roof-frame",
          dimension: "金步举高",
          formula: "stepSpan * 0.7",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "七举 0.7（梁思成图纸系数组第 2 架）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftThird",
          subjectConceptRef: "roof-frame",
          dimension: "上金步举高",
          formula: "stepSpan * 0.8",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "八举 0.8（梁思成图纸系数组第 3 架）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftFourth",
          subjectConceptRef: "roof-frame",
          dimension: "脊步举高",
          formula: "stepSpan * 0.9",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "九举 0.9（梁思成图纸系数组第 4 架）",
          deviation: null,
          applicability: null,
        },
      ],
    },
    {
      schemaVersion: "rule-spec-1",
      ruleSetId: "qing-gongcheng-zuofa",
      sourceText: "清工程做法则例的推荐举架系数（转引自 ACA-Builder const.py LIFT_RATIO_SMALL 注释）",
      version: "1.0.0",
      rules: [
        {
          ruleId: "stepSpan",
          subjectConceptRef: "roof-frame",
          dimension: "均分步架",
          formula: "totalDepthMm / 2 / stepCount",
          baseParams: ["totalDepthMm", "stepCount"],
          tolerance: null,
          sourceText: "步架 =（通进深 / 2）/ 步架数（jiangshu JiangSuan v1.0 举架算法）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftFirst",
          subjectConceptRef: "roof-frame",
          dimension: "檐步举高",
          formula: "stepSpan * 0.5",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "五举 0.5（清工程做法系数组第 1 架）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftSecond",
          subjectConceptRef: "roof-frame",
          dimension: "金步举高",
          formula: "stepSpan * 0.65",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "六五举 0.65（清工程做法系数组第 2 架）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftThird",
          subjectConceptRef: "roof-frame",
          dimension: "上金步举高",
          formula: "stepSpan * 0.75",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "七五举 0.75（清工程做法系数组第 3 架）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "liftFourth",
          subjectConceptRef: "roof-frame",
          dimension: "脊步举高",
          formula: "stepSpan * 0.9",
          baseParams: [],
          tolerance: { kind: "ratio", value: "0.05" },
          sourceText: "九举 0.9（清工程做法系数组第 4 架）",
          deviation: null,
          applicability: null,
        },
        {
          ruleId: "eaveColumnHeight",
          subjectConceptRef: "eave-column",
          dimension: "檐柱高",
          formula: "byMeasurement",
          baseParams: [],
          tolerance: null,
          sourceText: "檐柱高按实计（jiangshu formulas.json 的按实计模式）",
          deviation: null,
          applicability: null,
        },
      ],
    },
  ],
} as const satisfies RuleDataFile;
