import type { DemoProjectDefinition } from "./definitions.js";

// 08 演示项目定义表 1 的两个演示项目。
// 一个演示资料充分时能产出什么，一个演示资料不足时会阻断什么，两个都用真实项目。

const HABS_RIGHTS = "美国历史建筑调查（HABS）成果，美国国家公园管理局说明属公共领域，可用于公开展示。";

// 1 英尺 = 304.8 mm。图面标注是英制，入库统一转毫米并保留原标注。
const FT = 304.8;
const feetInches = (feet: number, inches: number) => Math.round(feet * FT + inches * (FT / 12));

export const DAI_LOY_DEMO: DemoProjectDefinition = {
  demoId: "dai-loy-habs-ca-2071-w",
  projectName: "Dai Loy 赌馆博物馆测绘归档",
  buildingName: "Dai Loy 主楼",
  locationText: "美国加州萨克拉门托县 Locke 镇主街 13951 号",
  periodText: "约 1916 年",
  addressText: "13951 Main Street, Locke, Sacramento County, California",
  createdAt: "2026-08-18T00:00:00Z",
  limitationZh: "美国华人木构，不代表中国官式古建形制。它验证工程流程与制图质量，不证明中国古建构件识别能力。",
  sources: [
    {
      key: "sheet-16",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/03_HABS图纸16_首层与二层平面.jpg",
      fileName: "HABS图纸16_首层与二层平面.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 16 张：首层平面与二层平面",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "控制尺寸转写与平面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别。写明的标注为人工转写，没有标注的竖向尺寸为图上量取，两者已按存档级高分辨率版本核对。"],
    },
    {
      key: "sheet-17",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/04_HABS图纸17_剖面与西立面.jpg",
      fileName: "HABS图纸17_纵剖面A-A与西立面.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 17 张：纵剖面 A-A 与西立面",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "标高转写与立面、剖面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别。写明的标注为人工转写，没有标注的竖向尺寸为图上量取，两者已按存档级高分辨率版本核对。"],
    },
    {
      key: "sheet-18",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/05_HABS图纸18_剖面.jpg",
      fileName: "HABS图纸18_纵剖面B-B.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 18 张：纵剖面 B-B",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "内部构架关系与剖面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别。写明的标注为人工转写，没有标注的竖向尺寸为图上量取，两者已按存档级高分辨率版本核对。"],
    },
    {
      key: "site-photo",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/01_现场照片.png",
      fileName: "现场照片.png",
      mimeType: "image/png",
      evidenceType: "photo",
      title: "现场照片：主街立面现状",
      rightsDeclaration: "美国国家公园管理局公开图片。",
      intendedUse: "现状对照",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；照片未做构件识别。"],
    },
    {
      key: "nps-plan",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/02_首层平面教学图.png",
      fileName: "首层平面教学图.png",
      mimeType: "image/png",
      evidenceType: "drawing",
      title: "国家公园管理局首层平面说明图",
      rightsDeclaration: "美国国家公园管理局公开图片。",
      intendedUse: "房间功能对照，不作为尺寸依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["说明性图示，比例不可作为尺寸依据。"],
    },
    {
      key: "history-note",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/06_Dai_Loy历史与建筑说明.pdf",
      fileName: "Dai_Loy历史与建筑说明.pdf",
      mimeType: "application/pdf",
      evidenceType: "document",
      title: "历史与建筑说明",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "年代、材料与用途说明",
      recordedAt: null,
      // 由产品自己的解析器在构建期读文字层，正文与警告都不抄进定义
      parser: "pdf-text",
      parseStatus: "parsed",
      extractedText: null,
      parseWarnings: [],
      parseWithProduct: true,
    },
    {
      key: "field-notes",
      filePath: null,
      fileName: "现场测量笔记",
      mimeType: "application/pdf",
      evidenceType: "measurementRecord",
      title: "现场测量笔记（未数字化）",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "逐条尺寸的测量人、日期与方法",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "failed",
      extractedText: null,
      parseWarnings: [],
      absenceReasonZh: "HABS 公开记录未提供现场测量笔记的数字化件，逐条尺寸的测量人、日期与方法无法获得。",
    },
  ],
  facts: [
    {
      key: "structure-system",
      subject: "building",
      field: "structureSystemZh",
      value: "木构架，木桩与梁基础，窄板木外墙，压型金属屋面",
      evidenceKeys: ["sheet-17", "history-note"],
      reviewStatus: "unreviewed",
      dataStatus: "available",
    },
    {
      key: "floor-count",
      subject: "building",
      field: "floorCount",
      value: 2,
      evidenceKeys: ["sheet-16"],
      reviewStatus: "unreviewed",
      dataStatus: "available",
    },
    {
      key: "roof-form",
      subject: "building",
      field: "roofFormZh",
      value: "双坡，屋脊设采光气窗",
      evidenceKeys: ["sheet-17", "sheet-18"],
      reviewStatus: "unreviewed",
      dataStatus: "available",
    },
  ],
  // 尺寸分两类：图纸上写明的标注，与按图上量取的。两者精度差一个量级，
  // dataStatus 与 methodZh 都分开写，界面不把量取值当实测显示。
  //
  // 所有标注按同一批图纸的存档级高分辨率版本核对过。低分辨率版本上
  // 多条标注会被读错且读错时仍显得确定，核对记录见
  // 文档/05_验证证据/12_图纸差距与一致性核对/Dai_Loy读图与文字转写实测记录.md。
  measurements: [
    {
      key: "overall-width",
      subject: "building",
      quantity: { name: "overallWidthMm", value: feetInches(24, 0), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 24'-0\"",
      dataStatus: "available",
    },
    {
      key: "overall-depth",
      subject: "building",
      quantity: { name: "overallDepthMm", value: feetInches(60, 7), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 二层平面标注 60'-7\"",
      dataStatus: "available",
    },
    {
      key: "covered-alleyway-width",
      subject: "building",
      quantity: { name: "coveredAlleywayWidthMm", value: feetInches(8, 2), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 8'-2\"，尺寸线端点落在建筑北侧外墙线上，对应平面标注的 COVERED ALLEYWAY",
      dataStatus: "available",
    },
    {
      key: "alleyway-width",
      subject: "building",
      quantity: { name: "alleywayWidthMm", value: feetInches(7, 9), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 7'-9\"，尺寸线端点落在建筑南侧外墙线上，对应平面标注的 ALLEYWAY",
      dataStatus: "available",
    },
    {
      key: "covered-walk-depth",
      subject: "building",
      quantity: { name: "coveredWalkDepthMm", value: feetInches(7, 6), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 二层平面标注 7'-6\"。该尺寸接在 60'-7\" 之外的西端，按图面位置判为二层挑出覆盖步道的进深，图上没有文字说明这一归属",
      dataStatus: "uncertain",
    },
    {
      key: "ridge-elevation",
      subject: "building",
      quantity: { name: "ridgeElevationMm", value: feetInches(19, 6), unit: "mm" },
      evidenceKey: "sheet-17",
      methodZh: "转写自图纸 17 与图纸 18 标高 RIDGE ELEV 19'-6\"，基准为 FLOOR ELEV 0'",
      dataStatus: "available",
    },
    {
      key: "eave-elevation-scaled",
      subject: "building",
      quantity: { name: "scaledEaveElevationMm", value: 4460, unit: "mm" },
      evidenceKey: "sheet-17",
      methodZh: "图上量取，非实测。以图纸 17 上 RIDGE ELEV 19'-6\" 与 FLOOR ELEV 0' 两条标高线的间距校准（99.5 像素每英尺），再取西立面屋面在外墙面处的高度。量取误差约 ±50 mm",
      dataStatus: "uncertain",
    },
    {
      key: "second-floor-elevation-scaled",
      subject: "building",
      quantity: { name: "scaledSecondFloorElevationMm", value: 4130, unit: "mm" },
      evidenceKey: "sheet-18",
      methodZh: "图上量取，非实测。以图纸 18 的两条标高线校准，取剖面 B-B 上通长的二层楼面线。量取误差约 ±50 mm",
      dataStatus: "uncertain",
    },
    {
      key: "floor-above-grade-scaled",
      subject: "building",
      quantity: { name: "scaledFloorAboveGradeMm", value: 640, unit: "mm" },
      evidenceKey: "sheet-18",
      methodZh: "图上量取，非实测。取剖面 B-B 上楼面线与地坪线的间距。量取误差约 ±50 mm",
      dataStatus: "uncertain",
    },
  ],
  issues: [
    {
      key: "measurement-metadata-missing",
      issueType: "missingEvidence",
      descriptionZh: "逐条尺寸缺测量人、测量日期与测量方法。HABS 公开记录未数字化现场笔记，尺寸只能标为图面转写，不能算现场实测。正式资格因此阻断。",
      impactEvidenceKeys: ["field-notes", "sheet-16", "sheet-17"],
      blocksProxyOutcome: false,
    },
    {
      key: "transverse-section-absent",
      issueType: "missingEvidence",
      descriptionZh: "现有三张图纸只有两个纵剖面与一个西立面，没有横剖面、其余三个立面与节点详图。这些图种的成果没有可核对的原始依据，生成后须逐张人工复核。",
      impactEvidenceKeys: ["sheet-16", "sheet-17", "sheet-18"],
      blocksProxyOutcome: false,
    },
    {
      key: "typology-out-of-scope",
      issueType: "professionalUncertainty",
      descriptionZh: "本建筑是美国华人木构，不适用中国官式古建的形制规则与构件定名。规则层与词表的判断结论对本项目不成立。",
      impactEvidenceKeys: ["history-note"],
      blocksProxyOutcome: false,
    },
    {
      key: "overall-depth-source-conflict",
      issueType: "ruleConflict",
      descriptionZh: "建筑总进深两个来源不一致：历史与建筑说明写 approximately sixty feet deep，折 18288 mm；图纸 16 标注 60'-7\"，折 18470.6 mm。差 182.6 mm。文字是概述性表述，图纸是精确标注，但不自动选值，两个来源并列记录，由项目负责人核定后再改。本模型按图纸标注建。",
      impactEvidenceKeys: ["history-note", "sheet-16"],
      blocksProxyOutcome: false,
    },
    {
      key: "vertical-dimensions-scaled",
      issueType: "professionalUncertainty",
      descriptionZh: "图纸只标了屋脊与楼面两个标高，檐口高、二层楼面标高、层高与屋面坡度都没有标注。本项目的这几项按图上量取，以图纸自带的两条标高线校准，误差约 ±50 mm，坡度随檐口高的误差变化。量取值不能当实测用，须现场补测或取得带标注的剖面图后替换。",
      impactEvidenceKeys: ["sheet-17", "sheet-18"],
      blocksProxyOutcome: false,
    },
    {
      key: "low-resolution-misread",
      issueType: "highRisk",
      descriptionZh: "同一批图纸的低分辨率版本上，多条标注会被读成错值且读错时仍标为确定：8'-2\" 读成 8'-3\"、7'-9\" 读成 1'-9\"、屋脊 19'-6\" 两次分别读成 36'-0\" 与 31'-6\"。本项目全部标注已按存档级高分辨率版本核对。资料入库时应检查图纸分辨率，低分辨率图纸不能作为尺寸来源。",
      impactEvidenceKeys: ["sheet-16", "sheet-17", "sheet-18"],
      blocksProxyOutcome: false,
    },
    {
      key: "porch-extent-undocumented",
      issueType: "missingEvidence",
      descriptionZh: "首层平面在东端画出 PORCH，但没有标注它的进深与宽度，本模型未建前廊。补测或取得带标注的平面图后再补。",
      impactEvidenceKeys: ["sheet-16"],
      blocksProxyOutcome: false,
    },
  ],
  // 建筑局部坐标：X 沿总宽，0 在北侧（覆盖巷道一侧）外墙外皮；
  // Y 沿总长，0 在西端（主街一侧）外墙外皮；Z 自楼面标高 0' 起算。
  timberFrame: {
    sourceDeclarationZh: "尺寸分两类：drawn 是图纸上写明的标注，scaled 是按图上量取。量取以图纸自带的 RIDGE ELEV 19'-6\" 与 FLOOR ELEV 0' 两条标高线校准，误差约 ±50 mm。不套用任何中国官式形制规则。",
    dimensions: {
      width: {
        valueMm: feetInches(24, 0), source: "drawn", measurementKey: "overall-width",
        methodZh: "图纸 16 平面标注 24'-0\"", evidenceKeys: ["sheet-16"],
      },
      depth: {
        valueMm: feetInches(60, 7), source: "drawn", measurementKey: "overall-depth",
        methodZh: "图纸 16 二层平面标注 60'-7\"", evidenceKeys: ["sheet-16"],
      },
      ridgeElevation: {
        valueMm: feetInches(19, 6), source: "drawn", measurementKey: "ridge-elevation",
        methodZh: "图纸 17 与图纸 18 标高 RIDGE ELEV 19'-6\"", evidenceKeys: ["sheet-17", "sheet-18"],
      },
      eaveElevation: {
        valueMm: 4460, source: "scaled", measurementKey: "eave-elevation-scaled",
        methodZh: "图上量取西立面屋面在外墙面处的高度", evidenceKeys: ["sheet-17"],
      },
      secondFloorElevation: {
        valueMm: 4130, source: "scaled", measurementKey: "second-floor-elevation-scaled",
        methodZh: "图上量取剖面 B-B 的二层楼面线", evidenceKeys: ["sheet-18"],
      },
      floorAboveGrade: {
        valueMm: 640, source: "scaled", measurementKey: "floor-above-grade-scaled",
        methodZh: "图上量取剖面 B-B 楼面线与地坪线的间距", evidenceKeys: ["sheet-18"],
      },
      wallThickness: {
        valueMm: 140, source: "scaled",
        methodZh: "图上量取首层平面的外墙内外两条墙线间距", evidenceKeys: ["sheet-16"],
      },
      floorStructureDepth: {
        valueMm: 200, source: "scaled",
        methodZh: "图上量取剖面 B-B 楼面线与搁栅底线的间距", evidenceKeys: ["sheet-18"],
      },
      roofThickness: {
        valueMm: 60, source: "scaled",
        methodZh: "图上量取剖面上屋面构造层的厚度，板型与实际厚度未记录", evidenceKeys: ["sheet-17"],
      },
      eaveOverhang: {
        valueMm: 280, source: "scaled",
        methodZh: "图上量取西立面屋面挑出外墙面的水平距离", evidenceKeys: ["sheet-17"],
      },
      gableOverhang: {
        valueMm: 280, source: "scaled",
        methodZh: "图上量取西立面屋面挑出山墙面的水平距离", evidenceKeys: ["sheet-17"],
      },
      girderDepth: {
        valueMm: 200, source: "scaled",
        methodZh: "图上量取剖面 B-B 承台梁的高度", evidenceKeys: ["sheet-18"],
      },
      pierSize: {
        valueMm: 200, source: "scaled",
        methodZh: "图上量取剖面 B-B 木桩的宽度", evidenceKeys: ["sheet-18"],
      },
      partitionThickness: {
        valueMm: 120, source: "scaled",
        methodZh: "图上量取首层平面隔墙两条墙线的间距", evidenceKeys: ["sheet-16"],
      },
      pierSpacing: {
        valueMm: 2400, source: "scaled",
        methodZh: "图上量取剖面 B-B 木桩的中距，桩位在 1/4 英寸比例下量不准，实际排布记未知项", evidenceKeys: ["sheet-18"],
      },
    },
    // 两个气窗的平面位置在首层平面与剖面 B-B 上各量一次，互相吻合到 0.3 m 以内。
    // 西侧气窗横向大致骑在屋脊上，东侧偏在北坡，按量到的位置摆，不按对称摆正。
    monitors: [
      {
        key: "monitor/west",
        fromXMm: feetInches(6, 10), toXMm: feetInches(16, 7),
        startYMm: feetInches(3, 6), endYMm: feetInches(12, 2), riseMm: 790,
        source: "scaled", evidenceKeys: ["sheet-16", "sheet-17", "sheet-18"],
        methodZh: "平面位置取首层平面 MONITOR ABOVE 虚线框，高出屋脊的高度取剖面 B-B 量取",
      },
      {
        key: "monitor/east",
        fromXMm: feetInches(4, 7), toXMm: feetInches(12, 6),
        startYMm: feetInches(19, 10), endYMm: feetInches(29, 6), riseMm: 1380,
        source: "scaled", evidenceKeys: ["sheet-16", "sheet-17", "sheet-18"],
        methodZh: "平面位置取首层平面 MONITOR ABOVE 虚线框，高出屋脊的高度取剖面 B-B 量取",
      },
    ],
    planScaled: {
      valueMm: 0, source: "scaled",
      methodZh: "在平面图上按 100 像素每英尺量取，量取误差约 ±80 mm。隔墙与二层楼板的范围都由此得出",
      evidenceKeys: ["sheet-16"],
    },
    // 首层隔墙取自首层平面，二层隔墙取自二层平面。房间名照抄图上标注，
    // 不另起中文名，避免把原图没有的判断带进来。
    partitions: [
      { key: "vestibule-east", displayNameZh: "门厅东隔墙 VESTIBULE", level: "first", fromXMm: feetInches(7, 10), toXMm: feetInches(8, 3), fromYMm: 0, toYMm: feetInches(5, 7) },
      { key: "vestibule-south", displayNameZh: "门厅南隔墙 VESTIBULE", level: "first", fromXMm: 0, toXMm: feetInches(8, 3), fromYMm: feetInches(5, 3), toYMm: feetInches(5, 8) },
      { key: "lottery-north", displayNameZh: "彩票室北隔墙 LOTTERY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(30, 2), toYMm: feetInches(30, 7) },
      { key: "lottery-west", displayNameZh: "彩票室西隔墙 LOTTERY ROOM", level: "first", fromXMm: feetInches(15, 10), toXMm: feetInches(16, 3), fromYMm: feetInches(30, 2), toYMm: feetInches(39, 6) },
      { key: "lottery-south", displayNameZh: "彩票室南隔墙 LOTTERY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(39, 3), toYMm: feetInches(39, 8) },
      { key: "money-north", displayNameZh: "账房北隔墙 MONEY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(42, 3), toYMm: feetInches(42, 8) },
      { key: "money-west", displayNameZh: "账房西隔墙 MONEY ROOM", level: "first", fromXMm: feetInches(15, 10), toXMm: feetInches(16, 3), fromYMm: feetInches(42, 3), toYMm: feetInches(50, 6) },
      { key: "money-south", displayNameZh: "账房南隔墙 MONEY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(50, 3), toYMm: feetInches(50, 8) },
      { key: "toilet-north", displayNameZh: "厕所北隔墙 TOILET", level: "first", fromXMm: 0, toXMm: feetInches(5, 6), fromYMm: feetInches(52, 7), toYMm: feetInches(53, 0) },
      { key: "toilet-east", displayNameZh: "厕所东隔墙 TOILET", level: "first", fromXMm: feetInches(5, 3), toXMm: feetInches(5, 8), fromYMm: feetInches(52, 7), toYMm: feetInches(60, 7) },
      { key: "store-north", displayNameZh: "储藏室北隔墙 STORE ROOM", level: "first", fromXMm: feetInches(10, 0), toXMm: feetInches(21, 0), fromYMm: feetInches(52, 10), toYMm: feetInches(53, 3) },
      { key: "store-west", displayNameZh: "储藏室西隔墙 STORE ROOM", level: "first", fromXMm: feetInches(9, 10), toXMm: feetInches(10, 3), fromYMm: feetInches(52, 10), toYMm: feetInches(60, 7) },
      { key: "store-middle", displayNameZh: "两间储藏室之间隔墙 STORE ROOM", level: "first", fromXMm: feetInches(15, 10), toXMm: feetInches(16, 3), fromYMm: feetInches(52, 10), toYMm: feetInches(60, 7) },
      { key: "bedroom-east-west", displayNameZh: "东卧室西隔墙 BEDROOM", level: "second", fromXMm: feetInches(15, 4), toXMm: feetInches(15, 9), fromYMm: feetInches(29, 6), toYMm: feetInches(53, 0) },
      { key: "bedroom-east-north", displayNameZh: "东卧室北隔墙 BEDROOM", level: "second", fromXMm: feetInches(15, 4), toXMm: feetInches(24, 0), fromYMm: feetInches(29, 6), toYMm: feetInches(29, 11) },
      { key: "south-rooms-north", displayNameZh: "南侧房间北隔墙 BEDROOM 与 STAIR HALL", level: "second", fromXMm: 0, toXMm: feetInches(15, 9), fromYMm: feetInches(52, 9), toYMm: feetInches(53, 2) },
      { key: "bedroom-south-east", displayNameZh: "南卧室东隔墙 BEDROOM", level: "second", fromXMm: feetInches(10, 10), toXMm: feetInches(11, 3), fromYMm: feetInches(53, 0), toYMm: feetInches(60, 7) },
    ],
    // 二层只在东侧卧室与南端房间处铺板，中部标 OPEN BELOW 不铺
    secondFloorDecks: [
      { key: "bedroom-east", displayNameZh: "二层东卧室楼板 BEDROOM", level: "second", fromXMm: feetInches(15, 4), toXMm: feetInches(24, 0), fromYMm: feetInches(29, 6), toYMm: feetInches(53, 0) },
      { key: "south-rooms", displayNameZh: "二层南端楼板 BEDROOM 与 STAIR HALL", level: "second", fromXMm: 0, toXMm: feetInches(24, 0), fromYMm: feetInches(52, 9), toYMm: feetInches(60, 7) },
    ],
    canopies: [
      {
        key: "canopy/covered-walk", displayNameZh: "覆盖步道顶棚",
        fromXMm: -feetInches(8, 2), toXMm: feetInches(24, 0) + feetInches(7, 9),
        fromYMm: -feetInches(7, 6), toYMm: 0,
        elevationMm: 3610, thicknessMm: 100,
        postXsMm: [-2510, 50, 2420, 4760, 7220], postSizeMm: 150,
        source: "scaled", evidenceKeys: ["sheet-16", "sheet-17"],
        methodZh: "横向范围按平面尺寸线的三段标注取满，进深取二层平面标注 7'-6\"，标高与柱位按图上量取",
      },
      {
        key: "canopy/covered-alleyway", displayNameZh: "覆盖巷道顶棚",
        fromXMm: -feetInches(8, 2), toXMm: 0,
        fromYMm: 0, toYMm: feetInches(60, 7),
        elevationMm: 3610, thicknessMm: 100,
        postXsMm: [], postSizeMm: 150,
        source: "scaled", evidenceKeys: ["sheet-16", "sheet-17"],
        methodZh: "宽度取平面标注 8'-2\"，标高按图上量取。顶棚为搭在相邻建筑上的单坡棚，图上看不出独立支柱",
      },
    ],
    materials: {
      pier: "木作", girder: "木作", floorStructure: "木作",
      wall: "木作", gableWall: "木作", partition: "木作",
      roofPlane: "金属板", monitorWall: "木作", monitorRoof: "金属板",
      canopy: "木作", canopyPost: "木作",
    },
  },
  task: {
    name: "Dai Loy 主楼现状测绘归档",
    scope: ["主楼本体", "覆盖步道与巷道范围"],
    regulationRefs: ["HABS 实测图记录标准"],
    deliverables: ["首层平面", "二层平面", "西立面", "纵剖面 A-A", "纵剖面 B-B"],
    confirmed: true,
    artifactRequirements: {
      titleZh: "Dai Loy 主楼现状测绘成组图纸",
      revisionLabel: "A",
      geometryTargetRoles: ["exteriorWall", "floorStructure", "roofPlane", "foundationPier", "canopy"],
      sheets: [
        { key: "sheet-plans", drawingNumber: "DL-01", displayLabelZh: "平面图", pageMm: [594, 420] },
        { key: "sheet-sections", drawingNumber: "DL-02", displayLabelZh: "立面与剖面图", pageMm: [594, 420] },
      ],
      views: [
        {
          key: "first-floor-plan", displayLabelZh: "首层平面图", drawingRef: "DL-01-1", kind: "floorPlan",
          scaleDenominator: 100, sheetKey: "sheet-plans",
          viewportRectMm: [30, 40, 136, 228], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          sectionPlane: { normal: [0, 0, 1], offsetMm: 1400 },
          sourceEvidenceKeys: ["sheet-16"],
        },
        {
          key: "second-floor-plan", displayLabelZh: "二层平面图", drawingRef: "DL-01-2", kind: "floorPlan",
          scaleDenominator: 100, sheetKey: "sheet-plans",
          viewportRectMm: [200, 40, 136, 228], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          sectionPlane: { normal: [0, 0, 1], offsetMm: 4300 },
          sourceEvidenceKeys: ["sheet-16"],
        },
        {
          key: "west-elevation", displayLabelZh: "西立面图", drawingRef: "DL-02-1", kind: "elevation",
          scaleDenominator: 100, sheetKey: "sheet-sections",
          viewportRectMm: [30, 40, 136, 100], direction: [0, 1, 0], right: [1, 0, 0], up: [0, 0, 1],
          sourceEvidenceKeys: ["sheet-17"],
        },
        {
          key: "section-aa", displayLabelZh: "纵剖面 A-A", drawingRef: "DL-02-2", kind: "longitudinalSection",
          scaleDenominator: 100, sheetKey: "sheet-sections",
          viewportRectMm: [200, 40, 240, 100], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          sectionPlane: { normal: [1, 0, 0], offsetMm: -1244 },
          sourceEvidenceKeys: ["sheet-17"],
        },
        {
          key: "section-bb", displayLabelZh: "纵剖面 B-B", drawingRef: "DL-02-3", kind: "longitudinalSection",
          scaleDenominator: 100, sheetKey: "sheet-sections",
          viewportRectMm: [200, 170, 240, 100], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          sectionPlane: { normal: [1, 0, 0], offsetMm: 3657 },
          sourceEvidenceKeys: ["sheet-18"],
        },
      ],
    },
  },
};

export const GAODU_DEMO: DemoProjectDefinition = {
  demoId: "gaodu-yuhuang-temple-main-hall",
  projectName: "高都玉皇庙主殿现状记录",
  buildingName: "玉皇庙院内主殿",
  locationText: "山西省晋城市泽州县高都镇",
  periodText: "待复核",
  addressText: "山西省晋城市泽州县高都镇玉皇庙",
  createdAt: "2026-08-18T00:00:00Z",
  limitationZh: "全部尺寸由照片比例推算，无实测基准。成果只能作为草图参考，不能作为测绘成果使用。",
  sources: [
    {
      key: "recognition-record",
      filePath: "文档/05_验证证据/02_PoC工作流验证/部件识别_高都玉皇庙正立面.json",
      fileName: "部件识别_正立面.json",
      mimeType: "application/json",
      evidenceType: "document",
      title: "正立面部件识别记录（照片比例推算）",
      rightsDeclaration: "识别记录为本项目产出；所引照片为 Wikimedia Commons CC BY-SA 4.0，作者 Windmemories。",
      intendedUse: "构件清单与估算尺寸来源",
      recordedAt: "2026-07-10T00:00:00Z",
      parser: "utf8-json",
      parseStatus: "parsed",
      extractedText: null,
      parseWarnings: ["记录自述为盲测：无文献尺寸辅助，全部尺寸标为估算。"],
    },
    {
      key: "front-elevation-photo",
      filePath: null,
      fileName: "主殿正立面照片.jpg",
      mimeType: "image/jpeg",
      evidenceType: "photo",
      title: "主殿正立面照片（Wikimedia Commons，作者 Windmemories，CC BY-SA 4.0）",
      rightsDeclaration: "Wikimedia Commons，作者 Windmemories，CC BY-SA 4.0，转载须署名并以相同方式共享。",
      intendedUse: "构件识别与现状对照",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "failed",
      extractedText: null,
      parseWarnings: [],
      absenceReasonZh: "照片原件未随包提供，公开发布前需确认署名与共享条款的落实方式。",
    },
    {
      key: "measured-baseline",
      filePath: null,
      fileName: "现场实测记录",
      mimeType: "application/pdf",
      evidenceType: "measurementRecord",
      title: "现场实测记录（不存在）",
      rightsDeclaration: null,
      intendedUse: "尺寸基准",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "failed",
      extractedText: null,
      parseWarnings: [],
      absenceReasonZh: "本项目没有做过现场实测，没有任何实测记录可以入库。",
    },
  ],
  facts: [
    {
      key: "bay-count",
      subject: "building",
      field: "bayCount",
      value: 3,
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
    {
      key: "column-material",
      subject: "building",
      field: "columnMaterialZh",
      value: "方形石檐柱，抹角，柱面阴刻楹联",
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
    {
      key: "front-porch",
      subject: "building",
      field: "frontPorchZh",
      value: "前檐敞廊，无门窗与墙体",
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
    {
      key: "bracket-set",
      subject: "building",
      field: "bracketSetZh",
      value: "密布小型斗拱，逐攒未清点",
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
  ],
  measurements: [
    {
      key: "column-height-assumed",
      subject: "building",
      quantity: { name: "assumedColumnHeightMm", value: 3400, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "基准假设值，非实测。其余尺寸全部按此值等比推算，该值一错全部跟着错。",
      dataStatus: "uncertain",
    },
    {
      key: "central-bay-width",
      subject: "building",
      quantity: { name: "centralBayWidthMm", value: 3600, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "side-bay-width",
      subject: "building",
      quantity: { name: "sideBayWidthMm", value: 3000, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "total-front-width",
      subject: "building",
      quantity: { name: "totalFrontWidthMm", value: 9600, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "ridge-height",
      subject: "building",
      quantity: { name: "ridgeHeightMm", value: 7200, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "eave-height",
      subject: "building",
      quantity: { name: "eaveHeightMm", value: 5200, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
  ],
  issues: [
    {
      key: "no-measured-baseline",
      issueType: "missingEvidence",
      descriptionZh: "项目没有任何现场实测记录。全部尺寸由照片比例推算，基准是假设的石檐柱净高 3400 mm。成果只能作为草图，不能作为测绘成果，正式资格阻断。补测清单：柱高、柱径、明间与次间面阔、檐口高、脊高、台基高，共六项须现场实测。",
      impactEvidenceKeys: ["measured-baseline", "recognition-record"],
      blocksProxyOutcome: false,
    },
    {
      key: "photo-not-in-package",
      issueType: "missingEvidence",
      descriptionZh: "构件识别所依据的现场照片未随包提供，构件结论无法在包内回溯到图像位置。照片补入后须重新核对识别结果。",
      impactEvidenceKeys: ["front-elevation-photo"],
      blocksProxyOutcome: false,
    },
    {
      key: "hall-name-unverified",
      issueType: "professionalUncertainty",
      descriptionZh: "院内具体殿座名称待复核。文物保护单位公布名称对应整组建筑，本次记录的是院内主殿，殿座定名未经文物管理方确认。",
      impactEvidenceKeys: ["recognition-record"],
      blocksProxyOutcome: false,
    },
    {
      key: "bracket-count-unknown",
      issueType: "professionalUncertainty",
      descriptionZh: "斗拱按连续示意带表达，未逐攒清点与定型。攒数、跳数与拱件形制均未确定，不能据此判断年代与形制等级。",
      impactEvidenceKeys: ["recognition-record"],
      blocksProxyOutcome: false,
    },
  ],
  task: {
    name: "高都玉皇庙主殿现状记录",
    scope: ["院内主殿正立面"],
    regulationRefs: [],
    deliverables: ["正立面图", "平面图", "横剖面图"],
    confirmed: true,
    artifactRequirements: {
      titleZh: "高都玉皇庙主殿现状记录成组图纸",
      revisionLabel: "A",
      geometryTargetRoles: ["column", "roof"],
      sheets: [
        { key: "sheet-elevation", drawingNumber: "GD-01", displayLabelZh: "正立面图", pageMm: [420, 297] },
        { key: "sheet-plan-section", drawingNumber: "GD-02", displayLabelZh: "平面与剖面图", pageMm: [420, 297] },
      ],
      views: [
        {
          key: "front-elevation", displayLabelZh: "正立面图", drawingRef: "GD-01-1", kind: "elevation",
          scaleDenominator: 50, sheetKey: "sheet-elevation",
          viewportRectMm: [20, 40, 380, 222], direction: [0, 1, 0], right: [1, 0, 0], up: [0, 0, 1],
          sourceEvidenceKeys: ["recognition-record"],
        },
        {
          key: "floor-plan", displayLabelZh: "平面图", drawingRef: "GD-02-1", kind: "floorPlan",
          // 台明连檐出算进图面后平面是 12.0 x 13.2 m，1:50 要 240 x 264 mm，
          // A3 可用区只有 372 x 228 mm，放不下。质量基准 5.4.8 以 A3 为常规图幅，
          // 5.4.6 的比例集含 1:100，平面与剖面取 1:100，正立面另出一张仍用 1:50。
          scaleDenominator: 100, sheetKey: "sheet-plan-section",
          viewportRectMm: [20, 40, 180, 222], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          // 平面图是水平剖切，不是俯视投影；没有剖切面画出来的是屋顶。
          // 剖切标高取台明顶面（500）之上 1200 mm。
          sectionPlane: { normal: [0, 0, 1], offsetMm: 1700 },
          sourceEvidenceKeys: ["recognition-record"],
        },
        {
          key: "transverse-section", displayLabelZh: "横剖面图", drawingRef: "GD-02-2", kind: "transverseSection",
          scaleDenominator: 100, sheetKey: "sheet-plan-section",
          viewportRectMm: [220, 40, 180, 222], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          // 剖切面落在明间与次间之间的柱缝上（面阔 3000+3600+3000，轴线在 x = -1800）。
          // 切在开间正中只能切到檩与瓦，梁架、柱、斗栱一根都切不到，
          // 质量基准 3.5 要的一榀构造链就断了。
          sectionPlane: { normal: [1, 0, 0], offsetMm: -1800 },
          sourceEvidenceKeys: ["recognition-record"],
        },
      ],
    },
  },
  // 形制参数：面阔与柱高等取自照片估算，步架与举高由规则集推算。
  // 每一项在生成时按 estimatedDimensionKeys 分别标注，界面如实显示。
  archetype: {
    ruleSetId: "qing-gongcheng-zuofa",
    moduleMm: 60,
    moduleNameZh: "斗口",
    moduleSourceZh: "按密布小斗栱做法取斗口 60 mm，为形制判断估值，待实测斗栱后校正",
    stepCount: 3,
    bayWidthsMm: [3000, 3600, 3000],
    depthMm: 9600,
    sourceDeclarationZh: "面阔、柱高、台基等取自照片比例推算，基准为石檐柱净高 3400 mm；步架与举高由清工程做法则例系数组推算；梁架截面按檐柱径估算，逐层递减一个斗口，规则集尚无带出处的梁截面条目。",
    componentDimensionsMm: {
      terraceHeight: 500, terraceProjection: 1200, stairTreadCount: 3, stairWidth: 2000,
      columnBaseHeight: 250, columnHeight: 3400, columnSize: 380,
      architraveHeight: 700, architraveThickness: 240,
      bracketLayerHeight: 900,
      beamWidth: 380, beamHeight: 480,
      purlinDiameter: 220, rafterDiameter: 90, rafterSpacing: 300,
      roofBoardThickness: 25, eaveProjection: 1200,
      tileCourseWidth: 200, tileThickness: 18, ridgeHeight: 600,
    },
    columnSection: "square",
    bracketSetsPerBay: 4,
    enclosure: { front: "open", sides: "walled", back: "walled" },
    materials: {
      terrace: "石作", stair: "石作", columnBase: "石作", column: "石作",
      architrave: "木作", beam: "木作", kingPost: "木作", bracket: "木作", purlin: "木作", rafter: "木作",
      roofBoard: "木作", tile: "瓦作", ridge: "瓦作", wall: "砖作",
      gable: "木作", flyRafter: "木作",
    },
    estimatedDimensionKeys: [
      "bayWidth1", "bayWidth2", "bayWidth3",
      "terraceHeight", "terraceProjection", "stairWidth",
      "columnBaseHeight", "columnHeight", "columnSize",
      "architraveHeight", "bracketLayerHeight", "eaveProjection", "ridgeHeight",
      "beamWidth", "beamHeight",
    ],
  },
};

export const DEMO_PROJECTS: readonly DemoProjectDefinition[] = [DAI_LOY_DEMO, GAODU_DEMO];
