import type { DemoProjectDefinition } from "./definitions.js";

// 08 演示项目定义表 1 的两个演示项目。
// 一个演示资料充分时能产出什么，一个演示资料不足时会阻断什么，两个都用真实项目。

const HABS_RIGHTS = "美国历史建筑调查（HABS）成果，美国国家公园管理局说明属公共领域，可用于公开展示。";

// 1 英尺 = 304.8 mm。图面标注是英制，入库统一转毫米并保留原标注。
const FT = 304.8;
const feetInches = (feet: number, inches: number) => Math.round(feet * FT + inches * (FT / 12));

export const DAI_LOY_DEMO: DemoProjectDefinition = {
  demoId: "dai-loy-habs-ca-2071-w",
  projectName: "Dai Loy 赌馆博物馆测绘归档",
  buildingName: "Dai Loy 主楼",
  locationText: "美国加州萨克拉门托县 Locke 镇主街 13951 号",
  periodText: "约 1916 年",
  addressText: "13951 Main Street, Locke, Sacramento County, California",
  createdAt: "2026-08-18T00:00:00Z",
  limitationZh: "美国华人木构，不代表中国官式古建形制。它验证工程流程与制图质量，不证明中国古建构件识别能力。",
  sources: [
    {
      key: "sheet-16",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/03_HABS图纸16_首层与二层平面.jpg",
      fileName: "HABS图纸16_首层与二层平面.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 16 张：首层平面与二层平面",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "控制尺寸转写与平面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别，尺寸为人工转写。"],
    },
    {
      key: "sheet-17",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/04_HABS图纸17_剖面与西立面.jpg",
      fileName: "HABS图纸17_纵剖面A-A与西立面.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 17 张：纵剖面 A-A 与西立面",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "标高转写与立面、剖面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别，尺寸为人工转写。"],
    },
    {
      key: "sheet-18",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/05_HABS图纸18_剖面.jpg",
      fileName: "HABS图纸18_纵剖面B-B.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 18 张：纵剖面 B-B",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "内部构架关系与剖面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别，尺寸为人工转写。"],
    },
    {
      key: "site-photo",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/01_现场照片.png",
      fileName: "现场照片.png",
      mimeType: "image/png",
      evidenceType: "photo",
      title: "现场照片：主街立面现状",
      rightsDeclaration: "美国国家公园管理局公开图片。",
      intendedUse: "现状对照",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；照片未做构件识别。"],
    },
    {
      key: "nps-plan",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/02_首层平面教学图.png",
      fileName: "首层平面教学图.png",
      mimeType: "image/png",
      evidenceType: "drawing",
      title: "国家公园管理局首层平面说明图",
      rightsDeclaration: "美国国家公园管理局公开图片。",
      intendedUse: "房间功能对照，不作为尺寸依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["说明性图示，比例不可作为尺寸依据。"],
    },
    {
      key: "history-note",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/06_Dai_Loy历史与建筑说明.pdf",
      fileName: "Dai_Loy历史与建筑说明.pdf",
      mimeType: "application/pdf",
      evidenceType: "document",
      title: "历史与建筑说明",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "年代、材料与用途说明",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "pending",
      extractedText: null,
      parseWarnings: ["原始文件已保存；本里程碑未对该格式提取正文。"],
    },
    {
      key: "field-notes",
      filePath: null,
      fileName: "现场测量笔记",
      mimeType: "application/pdf",
      evidenceType: "measurementRecord",
      title: "现场测量笔记（未数字化）",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "逐条尺寸的测量人、日期与方法",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "failed",
      extractedText: null,
      parseWarnings: [],
      absenceReasonZh: "HABS 公开记录未提供现场测量笔记的数字化件，逐条尺寸的测量人、日期与方法无法获得。",
    },
  ],
  facts: [
    {
      key: "structure-system",
      subject: "building",
      field: "structureSystemZh",
      value: "木构架，木桩与梁基础，窄板木外墙，压型金属屋面",
      evidenceKeys: ["sheet-17", "history-note"],
      reviewStatus: "unreviewed",
      dataStatus: "available",
    },
    {
      key: "floor-count",
      subject: "building",
      field: "floorCount",
      value: 2,
      evidenceKeys: ["sheet-16"],
      reviewStatus: "unreviewed",
      dataStatus: "available",
    },
    {
      key: "roof-form",
      subject: "building",
      field: "roofFormZh",
      value: "双坡，屋脊设采光气窗",
      evidenceKeys: ["sheet-17", "sheet-18"],
      reviewStatus: "unreviewed",
      dataStatus: "available",
    },
  ],
  measurements: [
    {
      key: "overall-width",
      subject: "building",
      quantity: { name: "overallWidthMm", value: feetInches(24, 0), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 24'-0\"",
      dataStatus: "available",
    },
    {
      key: "overall-depth",
      subject: "building",
      quantity: { name: "overallDepthMm", value: feetInches(60, 7), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 60'-7\"",
      dataStatus: "available",
    },
    {
      key: "covered-walk-width",
      subject: "building",
      quantity: { name: "coveredWalkWidthMm", value: feetInches(8, 2), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 8'-2\"",
      dataStatus: "available",
    },
    {
      key: "alleyway-width",
      subject: "building",
      quantity: { name: "alleywayWidthMm", value: feetInches(7, 9), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 7'-9\"",
      dataStatus: "available",
    },
    {
      key: "ridge-elevation",
      subject: "building",
      quantity: { name: "ridgeElevationMm", value: feetInches(14, 6), unit: "mm" },
      evidenceKey: "sheet-17",
      methodZh: "转写自图纸 17 标高 RIDGE ELEV 14'-6\"，基准为 FLOOR ELEV 0'",
      dataStatus: "available",
    },
  ],
  issues: [
    {
      key: "measurement-metadata-missing",
      issueType: "missingEvidence",
      descriptionZh: "逐条尺寸缺测量人、测量日期与测量方法。HABS 公开记录未数字化现场笔记，尺寸只能标为图面转写，不能算现场实测。正式资格因此阻断。",
      impactEvidenceKeys: ["field-notes", "sheet-16", "sheet-17"],
      blocksProxyOutcome: false,
    },
    {
      key: "transverse-section-absent",
      issueType: "missingEvidence",
      descriptionZh: "现有三张图纸只有两个纵剖面与一个西立面，没有横剖面、其余三个立面与节点详图。这些图种的成果没有可核对的原始依据，生成后须逐张人工复核。",
      impactEvidenceKeys: ["sheet-16", "sheet-17", "sheet-18"],
      blocksProxyOutcome: false,
    },
    {
      key: "typology-out-of-scope",
      issueType: "professionalUncertainty",
      descriptionZh: "本建筑是美国华人木构，不适用中国官式古建的形制规则与构件定名。规则层与词表的判断结论对本项目不成立。",
      impactEvidenceKeys: ["history-note"],
      blocksProxyOutcome: false,
    },
  ],
  task: {
    name: "Dai Loy 主楼现状测绘归档",
    scope: ["主楼本体", "覆盖步道与巷道范围"],
    regulationRefs: ["HABS 实测图记录标准"],
    deliverables: ["首层平面", "二层平面", "西立面", "纵剖面 A-A", "纵剖面 B-B"],
    confirmed: true,
    artifactRequirements: {
      titleZh: "Dai Loy 主楼现状测绘成组图纸",
      revisionLabel: "A",
      geometryTargetRoles: ["wall", "floor", "roof", "column"],
      sheets: [
        { key: "sheet-plans", drawingNumber: "DL-01", displayLabelZh: "平面图", pageMm: [420, 297] },
        { key: "sheet-sections", drawingNumber: "DL-02", displayLabelZh: "立面与剖面图", pageMm: [420, 297] },
      ],
      views: [
        {
          key: "first-floor-plan", displayLabelZh: "首层平面图", drawingRef: "DL-01-1", kind: "floorPlan",
          scaleDenominator: 50, sheetKey: "sheet-plans",
          viewportRectMm: [20, 20, 180, 250], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          sourceEvidenceKeys: ["sheet-16"],
        },
        {
          key: "second-floor-plan", displayLabelZh: "二层平面图", drawingRef: "DL-01-2", kind: "floorPlan",
          scaleDenominator: 50, sheetKey: "sheet-plans",
          viewportRectMm: [220, 20, 180, 250], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          sourceEvidenceKeys: ["sheet-16"],
        },
        {
          key: "west-elevation", displayLabelZh: "西立面图", drawingRef: "DL-02-1", kind: "elevation",
          scaleDenominator: 50, sheetKey: "sheet-sections",
          viewportRectMm: [20, 20, 180, 120], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          sourceEvidenceKeys: ["sheet-17"],
        },
        {
          key: "section-aa", displayLabelZh: "纵剖面 A-A", drawingRef: "DL-02-2", kind: "longitudinalSection",
          scaleDenominator: 50, sheetKey: "sheet-sections",
          viewportRectMm: [220, 20, 180, 120], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          sectionPlane: { normal: [1, 0, 0], offsetMm: feetInches(12, 0) },
          sourceEvidenceKeys: ["sheet-17"],
        },
        {
          key: "section-bb", displayLabelZh: "纵剖面 B-B", drawingRef: "DL-02-3", kind: "longitudinalSection",
          scaleDenominator: 50, sheetKey: "sheet-sections",
          viewportRectMm: [220, 155, 180, 120], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          sectionPlane: { normal: [1, 0, 0], offsetMm: feetInches(6, 0) },
          sourceEvidenceKeys: ["sheet-18"],
        },
      ],
    },
  },
};

export const GAODU_DEMO: DemoProjectDefinition = {
  demoId: "gaodu-yuhuang-temple-main-hall",
  projectName: "高都玉皇庙主殿现状记录",
  buildingName: "玉皇庙院内主殿",
  locationText: "山西省晋城市泽州县高都镇",
  periodText: "待复核",
  addressText: "山西省晋城市泽州县高都镇玉皇庙",
  createdAt: "2026-08-18T00:00:00Z",
  limitationZh: "全部尺寸由照片比例推算，无实测基准。成果只能作为草图参考，不能作为测绘成果使用。",
  sources: [
    {
      key: "recognition-record",
      filePath: "文档/05_验证证据/02_PoC工作流验证/部件识别_高都玉皇庙正立面.json",
      fileName: "部件识别_正立面.json",
      mimeType: "application/json",
      evidenceType: "document",
      title: "正立面部件识别记录（照片比例推算）",
      rightsDeclaration: "识别记录为本项目产出；所引照片为 Wikimedia Commons CC BY-SA 4.0，作者 Windmemories。",
      intendedUse: "构件清单与估算尺寸来源",
      recordedAt: "2026-07-10T00:00:00Z",
      parser: "utf8-json",
      parseStatus: "parsed",
      extractedText: null,
      parseWarnings: ["记录自述为盲测：无文献尺寸辅助，全部尺寸标为估算。"],
    },
    {
      key: "front-elevation-photo",
      filePath: null,
      fileName: "主殿正立面照片.jpg",
      mimeType: "image/jpeg",
      evidenceType: "photo",
      title: "主殿正立面照片（Wikimedia Commons，作者 Windmemories，CC BY-SA 4.0）",
      rightsDeclaration: "Wikimedia Commons，作者 Windmemories，CC BY-SA 4.0，转载须署名并以相同方式共享。",
      intendedUse: "构件识别与现状对照",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "failed",
      extractedText: null,
      parseWarnings: [],
      absenceReasonZh: "照片原件未随包提供，公开发布前需确认署名与共享条款的落实方式。",
    },
    {
      key: "measured-baseline",
      filePath: null,
      fileName: "现场实测记录",
      mimeType: "application/pdf",
      evidenceType: "measurementRecord",
      title: "现场实测记录（不存在）",
      rightsDeclaration: null,
      intendedUse: "尺寸基准",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "failed",
      extractedText: null,
      parseWarnings: [],
      absenceReasonZh: "本项目没有做过现场实测，没有任何实测记录可以入库。",
    },
  ],
  facts: [
    {
      key: "bay-count",
      subject: "building",
      field: "bayCount",
      value: 3,
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
    {
      key: "column-material",
      subject: "building",
      field: "columnMaterialZh",
      value: "方形石檐柱，抹角，柱面阴刻楹联",
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
    {
      key: "front-porch",
      subject: "building",
      field: "frontPorchZh",
      value: "前檐敞廊，无门窗与墙体",
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
    {
      key: "bracket-set",
      subject: "building",
      field: "bracketSetZh",
      value: "密布小型斗拱，逐攒未清点",
      evidenceKeys: ["recognition-record"],
      reviewStatus: "unreviewed",
      dataStatus: "uncertain",
    },
  ],
  measurements: [
    {
      key: "column-height-assumed",
      subject: "building",
      quantity: { name: "assumedColumnHeightMm", value: 3400, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "基准假设值，非实测。其余尺寸全部按此值等比推算，该值一错全部跟着错。",
      dataStatus: "uncertain",
    },
    {
      key: "central-bay-width",
      subject: "building",
      quantity: { name: "centralBayWidthMm", value: 3600, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "side-bay-width",
      subject: "building",
      quantity: { name: "sideBayWidthMm", value: 3000, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "total-front-width",
      subject: "building",
      quantity: { name: "totalFrontWidthMm", value: 9600, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "ridge-height",
      subject: "building",
      quantity: { name: "ridgeHeightMm", value: 7200, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
    {
      key: "eave-height",
      subject: "building",
      quantity: { name: "eaveHeightMm", value: 5200, unit: "mm" },
      evidenceKey: "recognition-record",
      methodZh: "照片比例推算，非实测",
      dataStatus: "uncertain",
    },
  ],
  issues: [
    {
      key: "no-measured-baseline",
      issueType: "missingEvidence",
      descriptionZh: "项目没有任何现场实测记录。全部尺寸由照片比例推算，基准是假设的石檐柱净高 3400 mm。成果只能作为草图，不能作为测绘成果，正式资格阻断。补测清单：柱高、柱径、明间与次间面阔、檐口高、脊高、台基高，共六项须现场实测。",
      impactEvidenceKeys: ["measured-baseline", "recognition-record"],
      blocksProxyOutcome: false,
    },
    {
      key: "photo-not-in-package",
      issueType: "missingEvidence",
      descriptionZh: "构件识别所依据的现场照片未随包提供，构件结论无法在包内回溯到图像位置。照片补入后须重新核对识别结果。",
      impactEvidenceKeys: ["front-elevation-photo"],
      blocksProxyOutcome: false,
    },
    {
      key: "hall-name-unverified",
      issueType: "professionalUncertainty",
      descriptionZh: "院内具体殿座名称待复核。文物保护单位公布名称对应整组建筑，本次记录的是院内主殿，殿座定名未经文物管理方确认。",
      impactEvidenceKeys: ["recognition-record"],
      blocksProxyOutcome: false,
    },
    {
      key: "bracket-count-unknown",
      issueType: "professionalUncertainty",
      descriptionZh: "斗拱按连续示意带表达，未逐攒清点与定型。攒数、跳数与拱件形制均未确定，不能据此判断年代与形制等级。",
      impactEvidenceKeys: ["recognition-record"],
      blocksProxyOutcome: false,
    },
  ],
  task: {
    name: "高都玉皇庙主殿现状记录",
    scope: ["院内主殿正立面"],
    regulationRefs: [],
    deliverables: ["正立面现状草图"],
    confirmed: true,
    artifactRequirements: {
      titleZh: "高都玉皇庙主殿正立面现状草图",
      revisionLabel: "A",
      geometryTargetRoles: ["column", "roof"],
      sheets: [
        { key: "sheet-elevation", drawingNumber: "GD-01", displayLabelZh: "正立面草图", pageMm: [420, 297] },
      ],
      views: [
        {
          key: "front-elevation", displayLabelZh: "正立面草图", drawingRef: "GD-01-1", kind: "elevation",
          scaleDenominator: 50, sheetKey: "sheet-elevation",
          viewportRectMm: [20, 20, 380, 250], direction: [0, 1, 0], right: [1, 0, 0], up: [0, 0, 1],
          sourceEvidenceKeys: ["recognition-record"],
        },
      ],
    },
  },
};

export const DEMO_PROJECTS: readonly DemoProjectDefinition[] = [DAI_LOY_DEMO, GAODU_DEMO];
